import type { CollationOptions } from "mongodb";

/*
 * Options of `@Index`. Paths inside (`fields`, `partialFilterExpression`, `weights`,
 * `wildcardProjection`) are checked against the class by the decorator.
 */

/**
 * Direction or kind of one index key.
 *
 * @example
 * ```ts
 * const direction: IndexDirection = "hashed";
 * ```
 */
export type IndexDirection = 1 | -1 | "text" | "hashed" | "2dsphere" | "2d";

/**
 * The keys of an index, in order.
 *
 * @example
 * ```ts
 * const fields: IndexFields = { name: 1, age: -1 };
 * ```
 */
export type IndexFields = Readonly<Record<string, IndexDirection>>;

/**
 * An operator condition inside a partial filter. The server accepts equality, `$exists: true`,
 * `$gt`/`$gte`/`$lt`/`$lte`, `$type`, `$in` and `$and`/`$or` at the top level (it rejects the rest).
 *
 * @example
 * ```ts
 * const condition: PartialFilterCondition = { $gt: 18 };
 * ```
 */
export interface PartialFilterCondition {
  /** Equality. */
  readonly $eq?: unknown;
  /** Only `true` is accepted by the server in an index filter. */
  readonly $exists?: true;
  /** Greater than. */
  readonly $gt?: unknown;
  /** Greater than or equal. */
  readonly $gte?: unknown;
  /** Less than. */
  readonly $lt?: unknown;
  /** Less than or equal. */
  readonly $lte?: unknown;
  /** BSON type alias or number. */
  readonly $type?: string | number;
  /** Equal to one of the values. */
  readonly $in?: readonly unknown[];
}

/**
 * A partial filter: paths of the class (checked by `@Index`) plus `$and` / `$or`.
 *
 * @example
 * ```ts
 * const filter: PartialFilter = { $and: [{ age: { $gt: 18 } }, { active: true }] };
 * ```
 */
export interface PartialFilter {
  /** All the filters must match. */
  readonly $and?: readonly PartialFilter[];
  /** At least one of the filters must match. */
  readonly $or?: readonly PartialFilter[];
  readonly [path: string]: unknown;
}

/**
 * Everything `@Index(fields, options)` accepts.
 *
 * @example
 * ```ts
 * const options: IndexOptions = { unique: true, partialFilterExpression: { active: true } };
 * ```
 */
export interface IndexOptions {
  /** The index name (generated by the server from the keys otherwise). */
  readonly name?: string;
  /** Rejects duplicate key values. */
  readonly unique?: true;
  /** Indexes only the documents that have the indexed field. */
  readonly sparse?: true;
  /** TTL: a single-field index on a `Date` field. */
  readonly expireAfterSeconds?: number;
  /** Hidden from the query planner (kept up to date). */
  readonly hidden?: true;
  /** Indexes only the documents that match the filter. */
  readonly partialFilterExpression?: PartialFilter;
  /** Collation of the index. */
  readonly collation?: CollationOptions;
  /** Text index: weight per field. */
  readonly weights?: Readonly<Record<string, number>>;
  /** Text index: the default language. */
  readonly default_language?: string;
  /** Text index: the document field that overrides the language. */
  readonly language_override?: string;
  /** Wildcard index: which paths to include (1) or exclude (0). */
  readonly wildcardProjection?: Readonly<Record<string, 0 | 1>>;
}

/**
 * An Atlas Search / Vector Search index description (not supported by a plain mongod).
 *
 * @example
 * ```ts
 * const options: SearchIndexOptions = { name: "default", definition: { mappings: { dynamic: true } } };
 * ```
 */
export interface SearchIndexOptions {
  /** The index name. */
  readonly name: string;
  /** `"search"` (default) or `"vectorSearch"`. */
  readonly type?: "search" | "vectorSearch";
  /** The index definition as the Atlas API expects it. */
  readonly definition: Readonly<Record<string, unknown>>;
}
