// Typemo.transaction                      (INTERNAL, typemo.transaction.attempts: 1)
//   └─ Typemo.updateOne (Account)         (CLIENT, typemo.transaction: true)
//        ├─ Typemo.step cast              (INTERNAL)
//        ├─ Typemo.step validate          (INTERNAL)
//        ├─ update                        (CLIENT, driver command)
//        └─ Typemo.step populate          (INTERNAL)
// Typemo.find (Account)                   (CLIENT, db.query.summary: "find accounts")
// Typemo.find.cursor (Account)            (cursor; cursor.batch event)
// Typemo.insertOne (Account)              (CLIENT, status ERROR, error.type: "DuplicateKeyError")
// Typemo.aggregate (database bank)        (CLIENT, connection.aggregate: no model or collection)
