/*
 * The public API of the query types and builders, re-exported by `src/index.ts` in one line so the
 * export blocks stay separate. Paths are relative to `src/query/`.
 */
export { QueryError } from "../errors/query-error.ts";
export type {
  ContractCheck,
  ContractMismatch,
  ExpectRows,
} from "../types/contract.ts";
export { Contract } from "../types/contract.ts";
export type {
  CreateInput,
  DataFields,
  IdInputOf,
  IdOf,
  InputOf,
  Int64String,
  JsonOf,
  Lean,
  LeanOf,
  ObjectForm,
  ObjectFormOf,
  Output,
  Plain,
  PlainJson,
  PlainOf,
  RefDocumentInput,
  Replacement,
  ServiceKeys,
  StringInputOf,
  UpdateInput,
} from "../types/document-forms.ts";
export type {
  ArrayOperators,
  BitmaskOperand,
  CompareOf,
  Condition,
  ElemMatchOperand,
  FieldConditions,
  Filter,
  FilterPaths,
  FilterValue,
  GeoOperators,
  Orderable,
  RootOperators,
  ScalarOperators,
  TypeOperand,
} from "../types/filter.ts";
export type {
  GeoBigPolygonCrs,
  GeoIntersectsOperand,
  GeoJsonGeometry,
  GeoJsonGeometryCollection,
  GeoJsonLike,
  GeoJsonLineString,
  GeoJsonMultiLineString,
  GeoJsonMultiPoint,
  GeoJsonMultiPolygon,
  GeoJsonPoint,
  GeoJsonPolygon,
  GeoJsonSimpleGeometry,
  GeoLinearRing,
  GeoNearOperand,
  GeoPosition,
  GeoWithinGeometry,
  GeoWithinOperand,
  LegacyPair,
} from "../types/geo-json.ts";
export type {
  ApplyNarrow,
  IsFinite,
  NarrowBase,
  NarrowExists,
  NarrowIn,
  NarrowNotIn,
  NoNarrowing,
} from "../types/narrow.ts";
export type {
  FilterCheck,
  FilterMapEntries,
  FilterProblems,
  IsMapEntryKey,
  WriteFilterCheck,
  WriteForm,
} from "../types/path-check.ts";
export type {
  MaxPathDepth,
  PathError,
  Paths,
  PathValue,
  PositionToken,
  WritableKeys,
  WritePaths,
  WriteValue,
} from "../types/paths.ts";
export type {
  AnyPopulatedField,
  ApplyPopulate,
  CheckedPopulatePath,
  DefaultShape,
  Depopulated,
  ExtractPopulationEntries,
  IsTransformed,
  LeanBase,
  MaxPopulateDepth,
  PopulateArgument,
  PopulateArgumentEntries,
  PopulatedField,
  PopulatedKeys,
  PopulatedOriginalOf,
  PopulatedValueOf,
  PopulateHintDepth,
  PopulateListCheck,
  PopulateObject,
  PopulateObjectCheck,
  PopulateObjectSpec,
  PopulatePathHint,
  PopulatePaths,
  PopulateQueryOptions,
  PopulateReport,
  PopulateShape,
  PopulateTargetOf,
  PopulationEntry,
  ReplaceEntries,
  SegmentTarget,
  TransformDoc,
  TransformId,
  WalkPopulate,
} from "../types/populate.ts";
export type {
  ApplyProjection,
  DefaultView,
  ElemMatchProjection,
  HiddenPaths,
  OmitPath,
  Projected,
  Projection,
  ProjectionCheck,
  ProjectionFlag,
  ProjectionModeCheck,
  ScoreDirection,
  SliceProjection,
  Sort,
  SortDirection,
  SortPath,
} from "../types/projection.ts";
export type {
  DeleteResult,
  ExplainResult,
  ExplainVerbosity,
  ModifyResult,
  QueryResult,
  ReadForm,
  ReadShape,
  ResultDoc,
  UpdateResult,
} from "../types/result.ts";
export type {
  ContractArgumentError,
  Selected,
  SelectedFields,
  SelectedJson,
  SelectedJsonFields,
  SelectedLean,
  SelectedLeanFields,
  SelectedOverrides,
} from "../types/selected.ts";
export type { Dec, Element, NonEmptyArray, Same, Simplify, UnionToIntersection } from "../types/type-utils.ts";
export type {
  AddToSetOperand,
  ArrayFilters,
  ArrayPaths,
  BitOperand,
  CurrentDatePaths,
  FindOneAndUpdateOptions,
  IntegerPaths,
  MapEntryPaths,
  NumericOperand,
  NumericPaths,
  OrderablePaths,
  PullOperand,
  PushOperand,
  PushSort,
  RenamePaths,
  RenameTarget,
  SetFields,
  SetValue,
  UnsetPaths,
  Update,
  UpdateCheck,
  UpdateOptions,
  UpdateProblems,
  WholeElement,
} from "../types/update.ts";
export { CountQuery } from "./count-query.ts";
export { type ExecOptions, ExecutableQuery } from "./executable-query.ts";
export { GeoJson } from "./geo-json-values.ts";
export type {
  DistinctValue,
  FindOneAndReplaceOptions,
  ModelOperations,
  PipelineFindOneAndUpdateOptions,
  PipelineUpdateOptions,
  ReplaceOptions,
  UpsertFound,
} from "./model-operations.ts";
export { OptionQuery } from "./option-query.ts";
export { ParsedQuery, type ParseSource } from "./parsed-query.ts";
export {
  type Hint,
  isQueryBuilder,
  QueryBuilder,
  type QueryBuilderConstructor,
  type QueryOf,
  type QueryOutput,
  type QueryState,
  type ResultOf,
  type WhereBuilder,
  type WhereOperand,
} from "./query-builder.ts";
export type {
  ApplyMask,
  MaskedQuery,
  MaskFunction,
  MaskPaths,
  MaskResult,
  MaskSource,
  MaskSpecCheck,
  MaskValue,
  MaskValueAt,
} from "./response-mask.ts";
export { WriteBuilder } from "./write-builder.ts";
