/*
 * `bun run forms:table`: writes the per-type table of from-mongoose-to-typemo/guides/value-forms.md from the ONE
 * BSON ↔ TS table (`BsonTypeTable`: the `forms` text of every row, which a hover test keeps equal to what the
 * compiler derives), between the markers of the guide. `bun run forms:table --check` only compares (exit code 1
 * when the guide is stale); the test `packages/typemo/test/guards/value-forms-doc.test.ts` does the same inside
 * `bun test`.
 *
 * Usage: `bun run forms:table [--check]`
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { type BsonTypeKey, type BsonTypeRow, BsonTypeTable } from "../packages/typemo/src/index.ts";

/** The guide. */
const GUIDE = resolve(import.meta.dir, "../from-mongoose-to-typemo/guides/value-forms.md");
/** The marker that starts the generated block of the guide. */
const START = "<!-- value-forms:start (generated by `bun run forms:table` from BsonTypeTable; do not edit) -->";
/** The marker that ends the generated block of the guide. */
const END = "<!-- value-forms:end -->";

/** The BSON name of each row as the guide shows it (the `$type` alias, with the Binary subtype). */
const NAMES: Readonly<Record<BsonTypeKey, string>> = {
  objectId: "ObjectId",
  string: "String",
  double: "Double",
  int32: "Int32",
  long: "Long (int64)",
  decimal128: "Decimal128",
  bool: "Boolean",
  date: "Date",
  binary: "Binary",
  uuid: "UUID",
  vector: "Vector",
  regex: "RegExp",
  timestamp: "Timestamp",
  minKey: "MinKey",
  maxKey: "MaxKey",
  null: "null",
  array: "массив",
  object: "поддокумент / nested",
  map: "Map (`Spec.map`)",
};

/** Formatting and applying the generated table. */
export class ValueFormsTable {
  /**
   * Every row of the table (scalars first, in table order).
   *
   * @returns The rows.
   */
  static rows(): readonly BsonTypeRow<BsonTypeKey>[] {
    return BsonTypeTable.keys.map(
      (key) =>
        (key in BsonTypeTable.scalars
          ? BsonTypeTable.scalars[key as keyof typeof BsonTypeTable.scalars]
          : BsonTypeTable.containers[key as keyof typeof BsonTypeTable.containers]) as BsonTypeRow<BsonTypeKey>,
    );
  }

  /**
   * The `$toObject()` form of a row: the lean form of every value (BSON values as they are), except a Map, which stays
   * a `Map` (`ObjectForm`) — the one place the two forms differ.
   *
   * @param row - A table row.
   * @returns The type text.
   */
  static objectForm(row: BsonTypeRow<BsonTypeKey>): string {
    return row.key === "map" ? "Map<string, ObjectFormOf<V>>" : row.forms.lean;
  }

  /**
   * A code-formatted table cell.
   *
   * @param text - The cell text.
   * @returns The Markdown cell with pipes escaped.
   */
  private static cell(text: string): string {
    return `\`${text.replaceAll("|", "\\|")}\``;
  }

  /**
   * The BSON column of a row.
   *
   * @param row - A table row.
   * @returns The BSON name, its `$type` alias and the binary subtype.
   */
  private static bson(row: BsonTypeRow<BsonTypeKey>): string {
    const subtype = row.subtype === undefined ? "" : `, подтип ${row.subtype}`;
    return `${NAMES[row.key]} (\`${row.alias}\`${subtype})`;
  }

  /**
   * The generated block (markers included).
   *
   * @returns The Markdown text.
   */
  static render(): string {
    const cell = ValueFormsTable.cell;
    const lines = [
      START,
      "",
      "| BSON (`$type`) | hydrated (поле документа) | `lean()` | `$toObject()` | `$toPlain()` / `.plain()` | `$toJSON()` |",
      "|---|---|---|---|---|---|",
      ...ValueFormsTable.rows().map(
        (row) =>
          `| ${ValueFormsTable.bson(row)} | ${cell(row.forms.hydrated)} | ${cell(row.forms.lean)} | ${cell(ValueFormsTable.objectForm(row))} | ${cell(row.forms.plain)} | ${cell(row.forms.json)} |`,
      ),
      "",
      END,
    ];
    return lines.join("\n");
  }

  /**
   * `text` with its generated block replaced by the current one.
   *
   * @param text - The guide's text.
   * @returns The updated text.
   * @throws Error - When the markers are missing.
   */
  static apply(text: string): string {
    const start = text.indexOf(START);
    const end = text.indexOf(END);
    if (start === -1 || end === -1 || end < start) {
      throw new Error(`value-forms.md: the markers of the generated table are missing (${START} … ${END})`);
    }
    return `${text.slice(0, start)}${ValueFormsTable.render()}${text.slice(end + END.length)}`;
  }

  /**
   * The guide as it is on disk.
   *
   * @returns The text.
   */
  static current(): string {
    return readFileSync(GUIDE, "utf8");
  }

  /**
   * Writes the guide (or, with `check`, only compares).
   *
   * @param check - Only compare; do not write.
   * @returns The process exit code: `1` when `check` finds the guide stale.
   */
  static run(check: boolean): number {
    const current = ValueFormsTable.current();
    const next = ValueFormsTable.apply(current);
    if (next === current) {
      console.info("from-mongoose-to-typemo/guides/value-forms.md is up to date");
      return 0;
    }
    if (check) {
      console.error("from-mongoose-to-typemo/guides/value-forms.md is stale: run `bun run forms:table`");
      return 1;
    }
    writeFileSync(GUIDE, next);
    console.info("from-mongoose-to-typemo/guides/value-forms.md: the table was regenerated");
    return 0;
  }
}

if (import.meta.main) process.exit(ValueFormsTable.run(process.argv.includes("--check")));
