import path from "node:path";
import type { ContestantId, ContestantResult, GroupId, RunResult, ScenarioResult } from "../harness/types.ts";
import { RegressionComparator, type RegressionReport } from "./regression.ts";

/** Report headings of the scenario groups. */
export const GROUP_TITLES: Readonly<Record<GroupId, string>> = {
  A: "A. Старт и схема",
  B: "B. Создание",
  C: "C. Чтение",
  D: "D. Курсоры и стриминг",
  E: "E. Гидрация и сериализация",
  F: "F. Обновления",
  G: "G. Путь save",
  H: "H. Удаление",
  I: "I. Populate",
  J: "J. Агрегации",
  K: "K. Транзакции",
  L: "L. Механизмы",
  M: "M. Коллекции в памяти",
  N: "N. Приведение и валидация",
  O: "O. Нагрузка (YCSB)",
  P: "P. Change streams",
  Q: "Q. Длительность и утечки",
  R: "R. Компилятор и IDE",
};

/** Short column names of the contestants. */
const SHORT: Readonly<Record<ContestantId, string>> = {
  driver: "driver",
  mongoose: "mongoose",
  "mongoose-safe": "m-safe",
  typemo: "typemo",
  "typemo-lean": "t-lean",
};

/** Column order of the contestants. */
const ORDER: readonly ContestantId[] = ["driver", "mongoose", "mongoose-safe", "typemo", "typemo-lean"];

/** Start marker of the generated block of the report file. */
export const AUTO_BEGIN = "<!-- AUTO:BEGIN (generated by packages/bench/src/report/markdown-report.ts) -->";
/** End marker of the generated block of the report file. */
export const AUTO_END = "<!-- AUTO:END -->";

/**
 * Markdown summary: per group, medians with ×N ratios against the driver and against Mongoose, memory
 * and command counts. Only the block between AUTO markers is rewritten; hand-written analysis around it stays.
 */
export class MarkdownReport {
  /** The report file. */
  static readonly DEFAULT_FILE = path.resolve(
    import.meta.dir,
    "../../../../from-mongoose-to-typemo/reports/benchmarks.md",
  );

  /**
   * Formats milliseconds with a precision that fits the magnitude.
   *
   * @param value - Milliseconds.
   * @returns The text, or a dash for a missing value.
   */
  static ms(value: number | undefined): string {
    if (value === undefined || Number.isNaN(value)) return "—";
    if (value >= 100) return value.toFixed(0);
    if (value >= 10) return value.toFixed(1);
    if (value >= 1) return value.toFixed(2);
    if (value >= 0.01) return value.toFixed(3);
    return value.toPrecision(2);
  }

  /**
   * A ratio `a ÷ b`, in bold when `a` is more than 10 % worse.
   *
   * @param a - The numerator.
   * @param b - The denominator.
   * @returns The text, or a dash when it cannot be computed.
   */
  static ratio(a: number | undefined, b: number | undefined): string {
    if (a === undefined || b === undefined || !(b > 0) || Number.isNaN(a)) return "—";
    const r = a / b;
    const text = `×${r >= 10 ? r.toFixed(0) : r.toFixed(2)}`;
    return r > 1.1 ? `**${text}**` : text;
  }

  /**
   * Formats bytes as megabytes.
   *
   * @param bytes - Bytes.
   * @returns The text, or a dash for a missing value.
   */
  static mb(bytes: number | undefined): string {
    return bytes === undefined ? "—" : `${(bytes / 1024 / 1024).toFixed(bytes > 100 * 1024 * 1024 ? 0 : 1)}`;
  }

  /**
   * Indexes a scenario's results by contestant.
   *
   * @param s - The scenario result.
   * @returns The map.
   */
  static byContestant(s: ScenarioResult): Map<ContestantId, ContestantResult> {
    return new Map(s.contestants.map((c) => [c.contestant, c]));
  }

  /**
   * A short table cell for a contestant's median time or state.
   *
   * @param c - The contestant's result.
   * @returns The text.
   */
  static cell(c: ContestantResult | undefined): string {
    if (c === undefined || c.status === "skipped") return "·";
    if (c.status === "error") return "ERR";
    const time = MarkdownReport.ms(c.time?.median);
    return c.status === "mismatch" ? `${time} ≠` : time;
  }

  /**
   * The command counts of every contestant, joined by slashes.
   *
   * @param s - The scenario result.
   * @returns The text, or a dash when no counts exist.
   */
  static commandsCell(s: ScenarioResult): string {
    const by = MarkdownReport.byContestant(s);
    const parts = ORDER.map((c) => by.get(c)?.commands?.commands);
    if (parts.every((p) => p === undefined)) return "—";
    return parts.map((p) => (p === undefined ? "·" : String(p))).join("/");
  }

  /**
   * The bytes of commands sent by Mongoose and by Typemo.
   *
   * @param s - The scenario result.
   * @returns `mongoose→typemo`, or a dash when a count is missing.
   */
  static bytesCell(s: ScenarioResult): string {
    const by = MarkdownReport.byContestant(s);
    const m = by.get("mongoose")?.commands;
    const t = by.get("typemo")?.commands;
    if (m === undefined || t === undefined) return "—";
    const kb = (n: number): string => (n >= 10_240 ? `${(n / 1024).toFixed(0)}K` : `${n}`);
    return `${kb(m.bytesOut)}→${kb(t.bytesOut)}`;
  }

  /**
   * Unit of a table: µs when every median is below 1 ms, otherwise ms.
   *
   * @param scenarios - The scenarios of the table.
   * @returns The unit label and the factor that converts milliseconds to it.
   */
  static unitFor(scenarios: readonly ScenarioResult[]): { readonly unit: string; readonly scale: number } {
    const medians = scenarios.flatMap((s) => s.contestants.map((c) => c.time?.median ?? 0));
    return medians.length > 0 && Math.max(...medians) < 1 ? { unit: "мкс", scale: 1000 } : { unit: "мс", scale: 1 };
  }

  /**
   * Formats a number with a precision that fits the magnitude.
   *
   * @param value - The number.
   * @returns The text, or a dash for a non-finite value.
   */
  static num(value: number): string {
    if (!Number.isFinite(value)) return "—";
    if (value >= 100) return value.toFixed(0);
    if (value >= 10) return value.toFixed(1);
    if (value >= 1) return value.toFixed(2);
    return value.toFixed(3);
  }

  /**
   * "0.43 (p95 0.51)" in the table unit; ERR / · / ≠ markers.
   *
   * @param c - The contestant's result.
   * @param scale - Converts milliseconds to the table unit.
   * @returns The cell text.
   */
  static timeCell(c: ContestantResult | undefined, scale: number): string {
    if (c === undefined || c.status === "skipped") return "·";
    if (c.status === "error" || c.time === undefined) return "ERR";
    const text = `${MarkdownReport.num(c.time.median * scale)} (p95 ${MarkdownReport.num(c.time.p95 * scale)})`;
    return c.status === "mismatch" ? `${text} ≠` : text;
  }

  /**
   * The median of a contestant that finished ok.
   *
   * @param c - The contestant's result.
   * @returns The median in milliseconds, or `undefined`.
   */
  static okMedian(c: ContestantResult | undefined): number | undefined {
    return c !== undefined && c.status === "ok" && c.time !== undefined ? c.time.median : undefined;
  }

  /**
   * A sentence like "Typemo в 1.52× медленнее Mongoose (0.65 мс против 0.43 мс)".
   *
   * @param who - The subject.
   * @param a - The subject's median, ms.
   * @param other - The other side, in the genitive case.
   * @param b - The other side's median, ms.
   * @returns The sentence.
   */
  static compare(who: string, a: number, other: string, b: number): string {
    const r = a / b;
    const pair = `(${MarkdownReport.ms(a)} мс против ${MarkdownReport.ms(b)} мс)`;
    if (Math.abs(r - 1) < 0.05) return `${who} на уровне ${other} (±5 %) ${pair}`;
    return r > 1
      ? `${who} в ${r.toFixed(2)}× медленнее ${other} ${pair}`
      : `${who} в ${(1 / r).toFixed(2)}× быстрее ${other} ${pair}`;
  }

  /**
   * One-sentence verdict of a row, so the reader does not have to decode ratios.
   *
   * @param s - The scenario result.
   * @returns The verdict.
   */
  static verdict(s: ScenarioResult): string {
    if (s.status === "failed") return `Сверка/выполнение не прошли: ${(s.problems[0] ?? "").slice(0, 120)}`;
    const by = MarkdownReport.byContestant(s);
    const t = MarkdownReport.okMedian(by.get("typemo"));
    const tl = MarkdownReport.okMedian(by.get("typemo-lean"));
    const m = MarkdownReport.okMedian(by.get("mongoose"));
    const d = MarkdownReport.okMedian(by.get("driver"));
    const parts: string[] = [];
    if (t !== undefined && m !== undefined) parts.push(MarkdownReport.compare("Typemo", t, "Mongoose", m));
    else if (t !== undefined && d !== undefined) parts.push(MarkdownReport.compare("Typemo", t, "драйвера", d));
    if (tl !== undefined && d !== undefined) parts.push(MarkdownReport.compare("lean", tl, "драйвера", d));
    else if (tl !== undefined && m !== undefined && t === undefined)
      parts.push(MarkdownReport.compare("lean", tl, "Mongoose", m));
    return parts.length === 0 ? "—" : `${parts.join("; ")}.`;
  }

  /**
   * The table of one group.
   *
   * @param scenarios - The group's results.
   * @returns The Markdown lines.
   */
  static groupTable(scenarios: readonly ScenarioResult[]): string[] {
    const { unit, scale } = MarkdownReport.unitFor(scenarios);
    const lines = [
      `| Сценарий | Размер (док. на оп.) | driver, ${unit} | mongoose, ${unit} | m-safe, ${unit} | typemo, ${unit} | t-lean, ${unit} | Typemo ÷ Mongoose (×, <1 = Typemo быстрее) | Typemo ÷ driver (×, <1 = Typemo быстрее) | t-lean ÷ driver (×, <1 = lean быстрее) | команд на оп. d/m/ms/t/tl | байт команд m→t | Вывод |`,
      "|---|---|---:|---:|---:|---:|---:|---:|---:|---:|---|---|---|",
    ];
    for (const s of scenarios) {
      const by = MarkdownReport.byContestant(s);
      const t = (c: ContestantId): number | undefined => MarkdownReport.okMedian(by.get(c));
      lines.push(
        `| \`${s.id}\` ${s.title} | ${s.size}${s.unitsPerOp > 1 ? ` (${s.unitsPerOp})` : ""} | ` +
          ORDER.map((c) => MarkdownReport.timeCell(by.get(c), scale)).join(" | ") +
          ` | ${MarkdownReport.ratio(t("typemo"), t("mongoose"))} | ${MarkdownReport.ratio(t("typemo"), t("driver"))}` +
          ` | ${MarkdownReport.ratio(t("typemo-lean"), t("driver"))}` +
          ` | ${MarkdownReport.commandsCell(s)} | ${MarkdownReport.bytesCell(s)} | ${MarkdownReport.verdict(s).replaceAll("|", "\\|")} |`,
      );
    }
    return lines;
  }

  /** The "how to read the numbers" section. */
  static readonly LEGEND: readonly string[] = [
    "## Как читать цифры",
    "",
    "- **Время** — медиана на ОДНУ операцию (одна операция может обрабатывать много документов: число в скобках в колонке «Размер»). Единица указана в заголовке колонки (мс или мкс). Рядом — **p95** (95 % операций не дольше).",
    "- **Отношения ×N** — «A ÷ B»: время A, делённое на время B. **Меньше 1 — A быстрее**, больше 1 — A медленнее. Пример: «Typemo ÷ Mongoose = ×1.50» значит, что Typemo в 1.5 раза медленнее Mongoose; «×0.80» — Typemo быстрее (тратит 80 % времени Mongoose). Жирным — хуже больше чем на 10 %.",
    "- **Вывод** — то же словами: кто быстрее, во сколько раз и абсолютные медианы обоих.",
    '- **Участники:** driver — чистый драйвер mongodb 7.6.0 («пол»); mongoose — Mongoose 9.10.2 по умолчанию; m-safe — Mongoose с runValidators, sanitizeFilter, strictQuery: "throw"; typemo — гидратированные документы Typemo; t-lean — Typemo `.lean()`. На записи t-lean не участвует (те же вызовы, что у typemo).',
    "- **Метки:** `·` — участник не участвует в сценарии; `ERR` — ошибка; `≠` — результат не совпал со сверкой (участник сделал другую работу — такой результат не считается).",
    "- **Команды** — сколько команд ушло на сервер за одну операцию (d/m/ms/t/tl = driver/mongoose/m-safe/typemo/t-lean); **байт** — объём отправленных команд Mongoose → Typemo.",
    "- **Память** (отдельные таблицы) — в МБ: удержано после GC при живом результате / рост кучи за операцию / прирост пикового RSS.",
    "",
  ];

  /**
   * The memory table of a group.
   *
   * @param scenarios - The group's results.
   * @returns The Markdown lines; empty when the group has no memory scenario.
   */
  static memoryTable(scenarios: readonly ScenarioResult[]): string[] {
    const mem = scenarios.filter((s) => s.kind === "memory");
    if (mem.length === 0) return [];
    const lines = [
      "",
      "Память, МБ (отдельный процесс на участника): удержано после GC при живом результате / рост кучи / прирост пикового RSS. Меньше — лучше.",
      "",
      `| Сценарий | Размер | ${ORDER.map((c) => SHORT[c]).join(" | ")} |`,
      `|---|---|${ORDER.map(() => "---:").join("|")}|`,
    ];
    for (const s of mem) {
      const by = MarkdownReport.byContestant(s);
      lines.push(
        `| \`${s.id}\` | ${s.size} | ` +
          ORDER.map((c) => {
            const m = by.get(c)?.memory;
            return m === undefined
              ? MarkdownReport.cell(by.get(c))
              : `${MarkdownReport.mb(m.retained)} / ${MarkdownReport.mb(m.heapDelta)} / ${MarkdownReport.mb(m.rssDelta)}`;
          }).join(" | ") +
          " |",
      );
    }
    return lines;
  }

  /**
   * The self-measured metrics of a group.
   *
   * @param scenarios - The group's results.
   * @returns The Markdown lines; empty when there are no metrics.
   */
  static metricsTable(scenarios: readonly ScenarioResult[]): string[] {
    const withMetrics = scenarios.filter((s) => s.contestants.some((c) => c.outcome?.metrics !== undefined));
    if (withMetrics.length === 0) return [];
    const lines = ["", "Собственные метрики сценариев (не сравниваются, только отчёт):", ""];
    for (const s of withMetrics) {
      lines.push(`- \`${s.id}\` (${s.size}):`);
      for (const c of s.contestants) {
        const m = c.outcome?.metrics;
        if (m === undefined) continue;
        const text = Object.entries(m)
          .map(([k, v]) => `${k}=${Number.isInteger(v) ? v : v.toFixed(2)}`)
          .join(", ");
        lines.push(`  - ${c.contestant}: ${text}`);
      }
    }
    return lines;
  }

  /**
   * The environment table.
   *
   * @param run - A run.
   * @returns The Markdown lines.
   */
  static environment(run: RunResult): string[] {
    const e = run.environment;
    return [
      "| Параметр | Значение |",
      "|---|---|",
      `| CPU | ${e.cpu}, ${e.cores} ядер, ${e.memoryGb} ГБ |`,
      `| ОС | ${e.os} |`,
      `| Bun | ${e.bun} |`,
      `| MongoDB | ${e.mongodb} (${e.mongodbTopology}), Docker-образ \`${e.dockerImage}\` |`,
      `| Драйвер mongodb | ${e.driver} (внутри Mongoose: ${e.mongooseDriver}) |`,
      `| Mongoose | ${e.mongoose} |`,
      `| Typemo | ${e.typemo} |`,
      `| mitata | ${e.mitata} |`,
      `| git | ${e.gitBranch} @ ${e.gitCommit.slice(0, 10)} |`,
    ];
  }

  /**
   * Scenarios where hydrated Typemo is more than 10 % slower than default Mongoose.
   *
   * @param runs - The runs.
   * @returns The Markdown lines.
   */
  static slowerThanMongoose(runs: readonly RunResult[]): string[] {
    const rows: { id: string; size: string; ratio: number; t: number; m: number }[] = [];
    for (const run of runs) {
      for (const s of run.scenarios) {
        const by = MarkdownReport.byContestant(s);
        const t = by.get("typemo");
        const m = by.get("mongoose");
        if (t?.status !== "ok" || m?.status !== "ok" || t.time === undefined || m.time === undefined) continue;
        const ratio = t.time.median / m.time.median;
        if (ratio > 1.1)
          rows.push({ id: `${s.id} [${run.profile}]`, size: s.size, ratio, t: t.time.median, m: m.time.median });
      }
    }
    rows.sort((a, b) => b.ratio - a.ratio);
    if (rows.length === 0)
      return ["Нет сценариев, где hydrated Typemo медленнее Mongoose (default) больше чем на 10 %."];
    return [
      "| Сценарий | Размер | typemo, мс | mongoose, мс | Typemo ÷ Mongoose (×, <1 = Typemo быстрее) | Вывод |",
      "|---|---|---:|---:|---:|---|",
      ...rows.map(
        (r) =>
          `| \`${r.id}\` | ${r.size} | ${MarkdownReport.ms(r.t)} | ${MarkdownReport.ms(r.m)} | ×${r.ratio.toFixed(2)} | ${MarkdownReport.compare("Typemo", r.t, "Mongoose", r.m)}. |`,
      ),
    ];
  }

  /**
   * The scenarios that did not finish ok.
   *
   * @param runs - The runs.
   * @returns The Markdown lines.
   */
  static problems(runs: readonly RunResult[]): string[] {
    const lines: string[] = [];
    for (const run of runs) {
      for (const s of run.scenarios) {
        if (s.status === "ok") continue;
        lines.push(
          `- \`${s.id}\` (${s.size}, ${run.profile}) — **${s.status}**: ${s.problems.join("; ").replaceAll("|", "\\|")}`,
        );
      }
    }
    return lines.length === 0 ? ["Все сценарии прошли сверку результатов."] : lines;
  }

  /**
   * The generated block of the report.
   *
   * @param runs - The runs; at least one.
   * @param regression - The comparison with a baseline, when there is one.
   * @returns The Markdown text, including the AUTO markers.
   * @throws Error - When there are no runs.
   */
  static render(runs: readonly RunResult[], regression?: RegressionReport): string {
    const first = runs[0];
    if (first === undefined) throw new Error("MarkdownReport: no runs");
    const out: string[] = [
      AUTO_BEGIN,
      "",
      ...MarkdownReport.LEGEND,
      "## Окружение",
      "",
      ...MarkdownReport.environment(first),
      "",
    ];
    out.push(
      "## Прогоны",
      "",
      "| Профиль | Начало | Длительность | Сценариев×размеров | ok / partial / failed | Файл |",
      "|---|---|---:|---:|---|---|",
    );
    for (const run of runs) {
      const count = (status: string): number => run.scenarios.filter((s) => s.status === status).length;
      out.push(
        `| ${run.profile} | ${run.startedAt} | ${(run.durationMs / 60_000).toFixed(1)} мин | ${run.scenarios.length} | ` +
          `${count("ok")} / ${count("partial")} / ${count("failed")} | \`results/${String(run.settings.file ?? "")}\` |`,
      );
    }
    out.push("");
    for (const run of runs) {
      out.push(`## Результаты: профиль \`${run.profile}\``, "");
      const groups = [...new Set(run.scenarios.map((s) => s.group))].sort();
      for (const group of groups) {
        const scenarios = run.scenarios.filter((s) => s.group === group);
        out.push(`### ${GROUP_TITLES[group]}`, "", ...MarkdownReport.groupTable(scenarios));
        out.push(...MarkdownReport.memoryTable(scenarios), ...MarkdownReport.metricsTable(scenarios), "");
      }
    }
    out.push(
      "## Где hydrated Typemo медленнее Mongoose (default) больше чем на 10 %",
      "",
      ...MarkdownReport.slowerThanMongoose(runs),
      "",
    );
    out.push("## Сверка результатов и ошибки", "", ...MarkdownReport.problems(runs), "");
    if (regression !== undefined) {
      out.push(
        "## Регрессии относительно базовой линии",
        "",
        "```",
        RegressionComparator.format(regression),
        "```",
        "",
      );
    }
    out.push(AUTO_END);
    return out.join("\n");
  }

  /**
   * Writes the report, keeping hand-written text outside the AUTO markers.
   *
   * @param runs - The runs.
   * @param file - The report file.
   * @param regression - The comparison with a baseline, when there is one.
   * @returns The file that was written.
   */
  static async write(
    runs: readonly RunResult[],
    file: string = MarkdownReport.DEFAULT_FILE,
    regression?: RegressionReport,
  ): Promise<string> {
    const auto = MarkdownReport.render(runs, regression);
    const existing = (await Bun.file(file).exists()) ? await Bun.file(file).text() : "";
    const begin = existing.indexOf(AUTO_BEGIN);
    const end = existing.indexOf(AUTO_END);
    const next =
      begin >= 0 && end > begin
        ? existing.slice(0, begin) + auto + existing.slice(end + AUTO_END.length)
        : `# Бенчмарки Typemo против Mongoose и драйвера\n\n${auto}\n`;
    await Bun.write(file, next);
    return file;
  }
}
